name: Android UI Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  android-integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Fetch Flutter dependencies
        run: flutter pub get

      - name: Start emulator and run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel_6
          script: |
            flutter config --no-analytics
            flutter pub get
            flutter drive \
              --driver=integration_test/driver.dart \
              --target=integration_test/app_test.dart

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-ui-test-screenshots
          path: build/integration_test_screenshots
          if-no-files-found: warn
